# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f35631a3e255c2155d833cfbe762b175de38e4e46d9f3eff2ce9e277163fe45c31022b27fcfe0b1f6f253a45e47cc27bc4691ce2cfbf548aef8aa593e2786990

test:
  secret_key_base: c6c864b010afc42249f8764cb5ffb9d47b2fdb67e737456e74bfaf4b2eb0ad4b38675fbc25f2aa11ceb7fd463bf103abe0172444ca82924fd6a2854bc7044161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#===[ Secrets ]=========================================================
#
# This file is meant for storing secret information that is never
# published or committed to a revision control system.
#
# Do not modify this "config/secrets.yml.sample" file directly -- you
# should copy it to "config/secrets.yml" and customize it there.
#
#---[ Values ]----------------------------------------------------------

# Email address of administrator that will get exception notifications
# and requests for assistance from users:
administrator_email: 'your@email.addr'

# Admin username and password to use when accessing /admin pages
admin_username: 'admin'
admin_password: 'kitties!'

# Secret code for verifying cookie session data integrity. If you change it,
# all old sessions will become invalid! Make sure the secret is at least 30
# characters and all random, no regular words or you'll be exposed to
# dictionary attacks.
session_secret: '1290832312281326461234712c347134618233441234513341132032545424856956711678856985f0575586671765c678659e7855bd58c6978856178b56e8f6'

# Name to use for storing application's session cookies, this is often a
# shortened form of your organization and application name, e.g.,
# "igniteportlandproposals", "igniteproposals", "openproposals", etc:
session_name: 'calagator'

# API key for Meetup.com, get your own from: http://www.meetup.com/meetup_api/key/
# meetup_api_key: registerNow

# Search engine to use for searching events, uncomment the line to specify that
# search engine. Defaults to 'sql'. For further information, see `INSTALL.md`.
### search_engine: sql
### search_engine: sunspot

# Configure a mapping provider
# Stamen's terrain tiles will be used by default.
# Map marker color
# Values: red, darkred, orange, green, darkgreen, blue, purple, darkpuple, cadetblue
mapping_marker_color: green

# A Google Maps API key is required to use Google's geocoding service
# as well as to display maps using their API.
#
# Get one at: https://developers.google.com/maps/documentation/javascript/tutorial#api_key
mapping_google_maps_api_key: <your google maps v3 API key>

# The tile provider to use when rendering maps with Leaflet.
# One of: leaflet, stamen, mapbox, google
# mapping_provider: stamen
#
# The tiles to use for the map, see the docs for individual Leaflet plugins.
# For stamen, this can be one of: terrain, toner, watercolor
# mapping_tiles: terrain
#
#== Examples ==
# Stamen
# (available tiles: terrain, toner, watercolor)
# mapping_provider: stamen
# mapping_tiles: watercolor
#
# MapBox Streets (use a map from your own account)
# mapping_provider: mapbox
# mapping_tiles: examples.map-9ijuk24y
#
# Google Maps
# mapping_provider: google
# mapping_tiles: ROADMAP
# mapping_google_maps_api_key: <your google maps v3 API key>
#
# OpenStreetMap
# mapping_provider: leaflet
# mapping_tiles: http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
#
# Esri
# (available tiles: Gray, Streets, Oceans, Topographic)
# mapping_provider: esri
# mapping_tiles: Gray

#===[ fin ]=============================================================
